# Generated by Django 5.2.2 on 2025-06-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('price_type', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('RUB', '₽'), ('UZS', "so'm")], default='USD', max_length=10)),
                ('unit_type', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kilogramm'), ('g', 'Gramm'), ('l', 'Litr'), ('ml', 'Millilitr'), ('m', 'Metr'), ('sm', 'Santimetr'), ('m2', 'Kvadrat metr'), ('m3', 'Kub metr'), ('qop', 'Qop'), ('blok', 'Blok'), ('dasta', 'Dasta'), ('paket', 'Paket'), ('karta', 'Karta')], default='dona', max_length=25)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_orign', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('check_status', models.CharField(blank=True, max_length=100, null=True)),
                ('min_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='fruitables.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
