# Generated by Django 5.2.2 on 2025-06-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Dona', 'dona'), ('Kilogramm', 'kg'), ('Gramm', 'g'), ('Litr', 'l'), ('Millilitr', 'ml'), ('Metr', 'm'), ('Santimetr', 'sm'), ('Kvadrat metr', 'm2'), ('Kub metr', 'm3'), ('Qop', 'qop'), ('Blok', 'blok'), ('Dasta', 'dasta'), ('Paket', 'paket'), ('Karta', 'karta')], default='Dona', max_length=25),
        ),
    ]
