# Generated by Django 5.2.2 on 2025-06-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0009_orderitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
