# Generated by Django 5.2.2 on 2025-06-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0011_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
