from django.urls import path

from .views import (
    profile_view,
    home_view,
    home_view2,
    logout_view,
    contact_view,
    register_view,
    login_view,
    change_password_view,
    shop_view,
    about_view,
    category_view,
    product_detail_view,
    testimonial_view,
    add_to_wishlist,
    remove_from_wishlist,
    wishlist_view,
    add_to_cart,
    remove_from_cart,
    cart_view,
)


urlpatterns = [
    path('', home_view, name='home'),
    path('home2/', home_view2, name='home2'),
    path('contact/', contact_view, name='contact'),
    path('profile/<int:pk>/', profile_view, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('change-password/', change_password_view, name='change_password'),
    path('shop/', shop_view, name='shop'),
    path('about/', about_view, name='about'),
    path('category/<slug:slug>/', category_view, name='category'),
    path('product-detail/<slug:slug>/', product_detail_view, name='product_detail'),
    path('testimonial/', testimonial_view, name='testimonial'),
    path('product/add-to-wishlist/<int:pk>/', add_to_wishlist, name='add_to_wishlist'),
    path('product/remove-from-wishlist/<int:pk>/', remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', wishlist_view, name='wishlist'),
    path('product/add-to-cart/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('product/remove-from-cart/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    path('cart/', cart_view, name='cart'),
]
